idf_component_register(
    SRCS
        "test_aes.c"
        "test_aon_otp.c"
        "test_calib_sync.c"
        "test_core.c"
        "test_fcmd.c"
        "test_gpio.c"
        "test_mac.c"
        "test_phy.c"
        "test_pmsc_pll.c"
        "test_sts.c"
        "test_txrx.c"
    INCLUDE_DIRS
        "."
    REQUIRES
        dw3000
        unity
)
